variables:
- name: myvar
  value: false
  
parameters:
- name: isTrue
  type: boolean
  default: false

jobs:
- job: A
  steps:
  - script: exit 1

- job: B
  dependsOn: A
  condition: and(failed(), eq(parameters.isTrue,true))
  steps:
  - script: echo A fails

- job: C
  dependsOn:
  - A
  - B
  condition: succeeded('B')
  steps:
  - script: echo B runs and succeeds
